INSERT INTO role (name) VALUES ('ROLE_ADMIN') ON CONFLICT (name) DO NOTHING;
INSERT INTO role (name) VALUES ('ROLE_ESTOQUISTA') ON CONFLICT (name) DO NOTHING;
INSERT INTO role (name) VALUES ('ROLE_CLIENTE') ON CONFLICT (name) DO NOTHING;

